Leaf/f5.2 hamburger menu
LetsMesh/Site pull request #184
Opened 2023-06-02 17:45 UTC by rllov

Created logged in home screen and side menu. There are some few minor adjustments/ bug/ gap issues I will create

2023-06-02 19:03 UTC, Shadowowl888 requested changes
Just some styling differences between your design and the sigma

2023-06-02 19:07 UTC, Shadowowl888 commented on src/Components/LoggedInPage.tsx
> +            </Button>
![Screen Shot 2023-06-02 at 12 05 06 PM](https://github.com/LetsMesh/Site/assets/75825603/ccb107ca-7156-480b-bf42-466490f7ea89)
Padding on the button is different from the figma

2023-06-02 19:09 UTC, Shadowowl888 commented on src/Components/LoggedInPage.tsx
> +import React from "react";
![Screen Shot 2023-06-02 at 12 07 58 PM](https://github.com/LetsMesh/Site/assets/75825603/9c2665e0-9732-45f6-bf53-cad350540df8)
If you want to change the font of the text to match the figma, the the cocogoose font should be in the main branch

2023-06-03 04:06 UTC, misslame requested changes

2023-06-03 04:06 UTC, misslame commented on src/Components/Images/NotifcationButton.png
these icons should come from an icon library.

2023-06-03 04:06 UTC, misslame commented on src/Components/Images/group_image.png
Could you move these images to the src folder instead of components as images are not components.

2023-06-03 04:06 UTC, misslame commented on src/Components/SideMenu.tsx
> +    // TODO: need to fix out icons for each.
If you make any TODO items, please make a github issue as well

2023-06-03 04:06 UTC, misslame commented on src/Components/login.css
> +
This seems like an unnecessary file

2023-07-29 15:37 UTC, misslame commented
This was completed via: 138

2023-07-29 15:37 UTC, closed without merging