Leaf/configure axios
LetsMesh/Site pull request #196
Opened 2023-06-09 06:20 UTC by owwix

- Axios configured. Front end can now communicate with django server. 
- CSRF middleware temporarily disabled, this will be reenabled once we properly implement CSRF tokens.

2023-06-10 05:08 UTC, rezatnoMsirhC requested changes

2023-06-10 05:08 UTC, rezatnoMsirhC commented on meshapp/src/config/axiosConfig.ts
I could see us needing to expand this from a "config" to a class in order to support and organize MeshApp-specific logic. Have you considered writing a wrapper-class here instead? For example, maybe we want to support a default error-handler for POST-requests without having to write out the try-catch every time.

2023-06-10 05:08 UTC, rezatnoMsirhC commented on meshapp/src/config/axiosConfig.ts
> +  });
How about adding a default-timeout here?

2023-06-14 01:43 UTC, owwix commented on meshapp/src/config/axiosConfig.ts
> +Then you can make calls as such -> axiosInstance.get(), axiosInstance.post(), etc
done 👍

2023-06-14 01:53 UTC, owwix commented on meshapp/src/config/axiosConfig.ts
> +  });
done 👍

2023-06-14 01:55 UTC, owwix commented on meshapp/src/config/axiosConfig.ts
> +import axios from "axios";
> How is this working without `axios` in [package.json](https://github.com/LetsMesh/Site/blob/leaf/configure_axios/meshapp/package.json#L5-L22)?

just fixed, pushed my package.json changes.

2023-06-16 18:01 UTC, owwix commented on meshapp/src/config/axiosConfig.ts
Created an issue for this: https://github.com/LetsMesh/Site/issues/211

2023-06-18 21:54 UTC, rezatnoMsirhC approved these changes

2023-06-22 02:24 UTC, Darren52BT approved these changes

2023-06-22 02:25 UTC, merged