Leaf/tables
LetsMesh/Site pull request #205
Opened 2023-06-16 01:47 UTC by peppacaiou

Fixed the messed-up url patterns. This code has been tested and certified working.

2023-06-16 14:57 UTC, misslame requested changes

2023-06-16 14:57 UTC, misslame commented on mesh/profiles/models.py
> +print(str(Account))
Why this print here?

2023-06-16 14:57 UTC, misslame commented on media/image/Clown_Emoji_Download_iPhone_Emojis.png
We only need one if youre going to keep this here

2023-06-16 14:57 UTC, misslame commented on media/image/Clown_Emoji_Download_iPhone_Emojis.png
Honestly tho, you should remove all of this

2023-06-16 16:49 UTC, PattyCakesxD approved these changes
Same concerns as Bob, lgtm otherwise

2023-06-23 01:27 UTC, closed without merging

2023-06-23 01:27 UTC, misslame commented
This code already in dev and targeted to wrong branch. 

Reopen if this was a mistake