Leaf/a4.7 http get call handling
LetsMesh/Site pull request #252
Opened 2023-07-11 02:25 UTC by GuyWhoCode

Closes #20 

## Features
- GET endpoint to return all the tags associated with a user given a userID
- Tests that mimic various scenarios that the GET endpoint might encounter
  - Includes using the tag model schema and inputting test data into a test database created by Django
- `template.env` file as a template for ENV variables to assign
- Refactor of Django migration files to match merged schema tables

## Notes
- All the migration files in this PR can be ignored (unless you want to really look at them) due to them being auto-generated by Django

2023-07-11 04:58 UTC, JRSiwiecki requested changes

2023-07-11 15:29 UTC, GuyWhoCode commented on mesh/urls.py
> +from mesh.tags import urls as tags
I didn't notice that the others had a naming convention. Changed.

2023-07-11 17:18 UTC, JRSiwiecki approved these changes
Looks good to me!

2023-07-13 20:15 UTC, K0725 approved these changes
Looks good to me! Well structured test cases too!

2023-07-13 20:24 UTC, merged