Leaf/a3.4 http get call handling
LetsMesh/Site pull request #271
Opened 2023-08-01 04:57 UTC by shotoh

issue #25

2023-08-03 03:50 UTC, misslame requested changes
I see some improvements that can be done.

2023-08-03 03:50 UTC, misslame commented on mesh/profiles/views.py
> +        profile = get_profile(request.GET, response)
Setting up a response as a success before actually determining if its successful is bad practice.

2023-08-03 03:50 UTC, misslame commented on mesh/profiles/views.py
> +            })
There are no error handlings. What if the profile is none? Right now it will return a success.

2023-08-03 03:50 UTC, misslame commented on mesh/profiles/views.py
> +    if request.method == "GET":
Same as above comments. Error handling and communicating

2023-08-03 03:50 UTC, misslame commented on mesh/profiles/views.py
> +        response.update({"status": "error"})
We should utilize exception handling here as previously done. Exception library json response formatting I believe was already done, it should be used.

2023-08-08 04:25 UTC, misslame commented
It still looks like you're doing repetitive error handling. 

Is a format like the following possible
try: 
   if valid get, 
       get the thing return response
  else 
       throw exception
except:

2023-08-09 00:11 UTC, celinem13 commented
It's possible to handle most if not all error cases if you use a try catch. i believe you can do multiple tries and a single catch unless you want to specify whats the error.

2023-08-09 03:19 UTC, misslame approved these changes
A lot better! Woot

2023-08-09 03:20 UTC, misslame commented on mesh/profiles/views.py
> +            "status": "success",
Can you use http codes?

2023-08-09 03:25 UTC, shotoh commented on mesh/profiles/views.py
> +            "status": "success",
done

2023-08-11 18:52 UTC, JRSiwiecki approved these changes
👍🏼

2023-08-16 23:46 UTC, JRSiwiecki commented on mesh/profiles/views.py
> +        }, status=400)
Change this to a `404 Not Found` status probably.

2023-08-16 23:51 UTC, JRSiwiecki commented on mesh/profiles/urls.py
> +    path("preferredPronouns", profile_views.PreferredPronounsView.as_view(), name="preferred_pronouns"),
This is purely a subjective ask, but can we try to use either kebab-case or snake_case in urls?

2023-08-16 23:52 UTC, JRSiwiecki requested changes
I made some small comments, ping me on discord after you take a look at them so I can approve your PR.

Good work though! Great idea with the get_data method 👍🏼

2023-08-16 23:59 UTC, misslame approved these changes
Approving again with new changes. Just one question that doesn't seem incredibly important

2023-08-16 23:59 UTC, misslame commented on mesh/utils/validate_data.py
> +def validate_required_fields(data, required_fields):
Just a question but why wouldn't you want to validate the json along with the fields? I see you use this method instead of using the json one...

2023-08-17 00:04 UTC, JRSiwiecki approved these changes

2023-08-17 01:15 UTC, misslame commented on mesh/profiles/views.py
> +        profile = Profile.objects.get(accountID=int(account_id))
Here is where you'd call the validate json, and youd pass in the request body im pretty sure

2023-08-17 18:34 UTC, merged